### ISSUE TITLE
whitelisting

### ISSUE THREAD

**Issue by unrealghostgamer** [mushroomhostage/exphc#26]
not sure where to go to get whitelisted so IGN:unrealghostgamer & IGN:Cameron_Bunney

**Comment by mushroomhostage** [comment]
Added you from your [reddit post](http://www.reddit.com/r/mcservers/comments/rzddb/anarchy_hardcore_pvp_experimental_hardcore/c4bcro3) :).

**Comment by mushroomhostage** [comment]
Note, anyone else trying to find out where to post to be whitelisted, try the link from the home page, I've clarified it a bit.
