### ISSUE TITLE
Missing radiation?

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#28]
Radiation was heavily nerfed, removing water and rain rads, and background radiation, but crater radiation is still intended -- need to verify it still works.

**Comment by unrealghostgamer** [comment]
havent found a crater and only 1 shelter. any chance of making the server gen more or is there a way to find them

**Comment by mushroomhostage** [comment]
That's cool you found a shelter already :) I haven't found one yet legit on this map but I know they're there. I've found craters, though (very noticeable because they were causing lag in the past due to the thousands of item drops, which IIRC should be improved now). 

Both craters and fallout shelters are generated in 0.1% of chunks, the default for CMA. Craters used to be much more frequent in earlier versions of the plugin but they were scaled back since the excessive radiation made the game too difficult (this was on the BlockTopia Solitude server, one of the earlier iterations). On ExpHC 1.1 they were even rarer because of problems in world generation, occurring in only about 33% of the possible chunks, but this problem was fixed in the ExpHC 1.2.3 map so they should be as frequent as configured. 

Increasing their frequency could be possible but to do it right would require regenerating the world. To find them you can try searching the land in an AnimalBike or Hot Air Balloon, but it's true they can be hard to spot, since only the trapdoor entrance of the shelter is visible from the ground. There isn't any way yet to specifically seek out shelters, nothing like an OD/OV scanner or metal detector or divining rod for shelters, but that's a good idea (maybe they could search for bedrock above y>6?). On the other hand there is usually a good amount of loot in the shelters so they're meant to be fairly rare.

**Comment by unrealghostgamer** [comment]
the default is 0.001 perhaps change it to 0.1. and it isnt made of bedrock it is made of re-enforced stone so maybe a scanner does work.

**Comment by mushroomhostage** [comment]
Ah yes, I forgot I customized the fallout shelter building material, changing it from bedrock to reinforced stone. Maybe the easiest thing to do would be adding reinforced stone as a "valuable ore" to be recognized by IC2's ore value scanner http://wiki.industrial-craft.net/index.php?title=OV_Scanner - the list is customizable. 

For the generation frequency, 0.001 = 0.1%; changing it to 0.1 = 10% would make shelters extremely common, too common I think, and a change here would require wiping the map. Going to leave it as 0.001 for now, we'll see how well it works over time, if any other players have any other feedback too, whether they're too rare or too common or just right, will consider changing when/if there is the next map reset (none planned for now). I think enhancing the OV Scanner could work out well, need to investigate.

**Comment by unrealghostgamer** [comment]
how about changiing it to 0.05 if map is ever reset

**Comment by mushroomhostage** [comment]
Maybe, we'll see. Not sure when the map will be reset next, trying to avoid it for 1.2.5 since many people just started, will probably have to reset for 1.3 and change all of the mods and plugins as some update or need to be rewritten, but that could be a long way off, too far to tell. 0.05 is 50 times 0.001, may be too high though, right now there are 861 fallout shelters on the map, times fifty would be 43,050.. a ton. There were some concerns from other players when shelters were first introduced that they were too overpowered, even one.. some servers disable them completely, thousands may be going overboard. 

For the OV scanner shelter locator:

config/IC2.cfg
     valuableOres=14:3, 15:4, 16:1, 21:3, 56:5, 73:3

That's gold ore, iron ore, coal ore, lapis ore, diamond ore, redstone ore. Add RP2 ores (ruby, emerald, sapphire, etc. = 140), Forestry apatite ore (198), IC2 reinforced stone (231)

```
 valuableOres=14:3, 15:4, 16:1, 21:3, 56:5, 73:3, 140:4, 198:3, 231:10
```

Deployed, will take effect on next automatic server restart.

Verified radiation from craters works, though it does seem weak - but it works.
