### ISSUE TITLE
Smart Moving: install server side or configure clients

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#31]
Smart Moving is an optional mod allowed on ExpHC 1.2.3, but unlike in 1.1 the Bukkit server component is not installed, only the client side. While most of the movement features work fine, others can cause glitches.

**Comment by mushroomhostage** [comment]
Requested at http://www.mcportcentral.co.za/index.php?topic=2008.0

**Comment by mushroomhostage** [comment]
Official thread of Smart Moving: http://www.minecraftforum.net/topic/361430-125smp-smart-moving/

The author added Bukkit support in 1.2.4 but not 1.2.3. Can/will it be backported? If not, best option may be to disable the functions requiring server-side support (like crawling through gaps) and see if that fixes the occasional glitchiness (swimming?). But Smart Moving is already available for 1.2.5, so this problem may resolve itself once MCPC 1.2.5 is available and all mods are ported and ExpHC updates.

**Comment by mushroomhostage** [comment]
Consider for 1.2.5?

**Comment by mushroomhostage** [comment]
The v7.8 download has "SmartMoving Server for ModLoaderMp.zip" and "SmartMoving Client for ModLoaderMp.zip" in the zip but no Bukkit or FML port.

**Comment by unrealghostgamer** [comment]
i think that you should wait until 1.3 is out before u update

**Comment by mushroomhostage** [comment]
Might have to. I have a 1.2.5 test server running with many of the same mods but their are a few that haven't been ported, the biggest being [RedPower2 pr5b1](http://www.mcportcentral.co.za/index.php?topic=2209.0) and [Hot Air Balloons](http://www.mcportcentral.co.za/index.php?topic=2271.0). But my hope is they'll be ported eventually along with the other missing mods then I'll be able to update to 1.2.5 before 1.3 is out, and be on the latest release for a while, so we get all the important bug fixes on the most current version of Minecraft. At least for a couple months until 1.3 drops, followed by maybe an even longer wait for all the mods to update, we'll see. 

Anyways I have Smart Moving [installed on 1.2.5](https://github.com/mushroomhostage/exphc/wiki/Updating) (not yet launched due to the missing mods), so closing this bug.
