### ISSUE TITLE
Add generated factory ruins

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#32]
Add the abandoned factory and water mill ruins schematics from super.

**Comment by mushroomhostage** [comment]
Exported as .schematic, and WorldEdit can //paste, but block IDs need to be updated for IC^2 machines.

**Comment by unrealghostgamer** [comment]
this sounds like it could be interesting.

**Comment by mushroomhostage** [comment]
hope so :)

Looking into the blocks in MCEdit, unrecognized IDs include: 228:4 (19) = blockCable, 250:0 (18) = blockMachine, 246:0 (3) = blockGenerator, and tile entities: Cable, Generator, Empty Management, MFE. These match on 1.1 (from where the schematic was created) and 1.2.3 (current server)..

**Comment by mushroomhostage** [comment]
Its choking on block 228 (-28 + 256 = 228)

```
19:01:33 [SEVERE] java.lang.ArrayIndexOutOfBoundsException: -28
19:01:33 [SEVERE]   at org.bukkit.Material.getMaterial(Material.java:438)
19:01:33 [SEVERE]   at com.sk89q.worldedit.bukkit.BukkitWorld.isValidBlockType(BukkitWorld.java:844)
19:01:33 [SEVERE]   at com.sk89q.worldedit.EditSession.rawSetBlock(EditSession.java:178)
19:01:33 [SEVERE]   at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:731)
19:01:33 [SEVERE]   at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1265)
19:01:33 [SEVERE]   at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:204)
19:01:33 [SEVERE]   at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:44)
19:01:33 [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
19:01:33 [SEVERE]   at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:469)
19:01:33 [SEVERE]   at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:914)
19:01:33 [SEVERE]   at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:874)
19:01:33 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:857)
19:01:33 [SEVERE]   at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
19:01:33 [SEVERE]   at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
19:01:33 [SEVERE]   at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:118)
19:01:33 [SEVERE]   at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
19:01:33 [SEVERE]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:557)
19:01:33 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:455)
19:01:33 [SEVERE]   at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
```

https://github.com/sk89q/worldedit/blob/master/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java

```
  public boolean isValidBlockType(int type) {
      return type <= 255 && Material.getMaterial(type) != null;
  }
```

**Comment by mushroomhostage** [comment]
Occurred with WorldEdit 5.3, same error with 5.4 snapshot (Last build (#1142-8c36047), 3 days 14 hr ago) http://build.sk89q.com/job/WorldEdit/

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/worldedit/commit/0b9e0f5b5fef4c0d8078756ebf4eb86112cd805c

Now I can //paste the factories with errors. The macerator textures are missing and drop machine blocks only when wrenched, the generators are missing textures but their GUI can be opened, and the cables appear to be okay. Should be fine to generate like this, maybe even better than fully-working machines.

**Comment by mushroomhostage** [comment]
Sent pull request: https://github.com/sk89q/worldedit/pull/192

Able to use patched WorldEdit in the meantime.

**Comment by mushroomhostage** [comment]
http://dl.dropbox.com/u/65303659/Schematics.zip

**Comment by mushroomhostage** [comment]
Added structures! They're _very_ rare (how rare exactly? secret :p) but their size somewhat balances out their rarity and they're all above or near the ground so they'll be easier to find than fallout shelters, in some sense (though there are many more fallout shelters than these abandoned structures).  

Be on the look out for abandoned factories and watermills near you :)

**Comment by mushroomhostage** [comment]
Sneak peak (no coordinates): http://imgur.com/a/ECuvC

**Comment by unrealghostgamer** [comment]
ahhhhhhhhhh no coordinates :(
