### ISSUE TITLE
Client-side lag near Trees++ forests

### ISSUE THREAD

**Issue by unrealghostgamer** [mushroomhostage/exphc#33]
loading the differnet trees are making my game lag bad. do you know any way to stop the lag ive tried gamebooster, more ram, optifine.

**Comment by mushroomhostage** [comment]
I assume you mean Trees++ not Forestry.. Forestry adds new machines and stuff relating to trees; Trees++ is the mid adding all those awesome (but sometimes processor-intensive, unfortunately) trees. 

Try this from https://github.com/mushroomhostage/exphc/wiki/Troubleshooting :

> If you notice lag near trees, in config/Trees++.cfg, change "Fancy Graphics=true" to "Fancy Graphics=false"

Hopefully that should help, another user reported the same problem and changing this config option worked for him, let me know if it improves performance for you (if not unfortunately the only fix may be a faster graphics card, or avoiding dense forests, but I'm hoping it doesn't come to that :)).

**Comment by unrealghostgamer** [comment]
will try when i can. my computer is only a few months old so i dont think it is card as i can run skyrim whle screen sharing it through skype without lag

**Comment by unrealghostgamer** [comment]
worked perfectly thanks

**Comment by mushroomhostage** [comment]
Great! Closing.
