### ISSUE TITLE
losing items

### ISSUE THREAD

**Issue by unrealghostgamer** [mushroomhostage/exphc#34]
are items ment to disapear to when u die? also what is the chances of seeing another player?

**Comment by mushroomhostage** [comment]
Item despawns on death is the same as in vanilla Minecraft, see here: http://www.minecraftwiki.net/wiki/Player_death#Death - basically, items will drop on death and persist for 5 minutes. 

Chances of seeing another player, depends on what you're doing :). If you hide out underground it can be very low especially with the ConeCloser mod which hides your nameplate until you are a few blocks away. If you build above ground chances of being discovered will be higher. To increase it further you can build a [radio beacon](http://dev.bukkit.org/server-mods/radiobeacon/) broadcasting a signal long distances (signals can travel thousands of blocks on this server), or use some of the advanced features of [RealisticChat](http://dev.bukkit.org/server-mods/realisticchat/).

**Comment by unrealghostgamer** [comment]
i have a beacon going and items only persist if chunk is loaded and im only player on mostly so is it a issue

**Comment by mushroomhostage** [comment]
Items should persist for 5 minutes if the chunk is loaded, or indefinitely if the chunk is unloaded. If you're seeing different behavior let me know :).

For getting more players, its a slow process, but I'm advertising more. Just posted on the [Bukkit forums](http://forums.bukkit.org/threads/exphc-hardcore-post-apocalyptic-modded-rp2%E2%80%A2ic2%E2%80%A2bc%E2%80%A2hot-air-balloons%E2%80%A2trees-%E2%80%A2animalbikes%E2%80%A2-and-more.70695/), we'll see if that gets more users..
