### ISSUE TITLE
not issue just me gloating

### ISSUE THREAD

**Issue by unrealghostgamer** [mushroomhostage/exphc#35]
am i pro or what just found my 2nd shelter

**Comment by mushroomhostage** [comment]
Nice :). Still haven't found one myself yet but I know another player has as well. 

By the way, feel free to post any discussion or comments on this server to the reddit thread: http://www.reddit.com/r/mcservers/comments/svsrv/anarchy_experimental_hardcore_postapocalyptic/ - its much more well-suited to general discussion than the issue tracker :)
