### ISSUE TITLE
Duping fruit salad

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#36]
Reports of duping Fruit Salad using the QuickBench. Crafted with two empty bowls, received a bunch of fruit salad for nothing, filling up the player inventory.

**Comment by mushroomhostage** [comment]
Fruit Salad is from Trees++. Need to reproduce. Also noticed Sturdy Machine from Foresty crafts into two instead of one. Quantity issue, maybe "-1" in the recipe output?

**Comment by unrealghostgamer** [comment]
first time i heard of fruit salad

**Comment by mushroomhostage** [comment]
It's an excellent food source, basically all I've been eating. 

Maybe related to number of different crafting recipes for the same result. Fruit salad can be crafted on dozens of different ways, with each kind of fruit. Sturdy Machine can be crafted two different ways, both with bronze, but the two types recognized by the Forge ore dictionary. Need to add individual item slots instead of using addItem() and having the crafting results stack, also need to match getRecipesForX on quantity, too.

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/QuickBench/commit/1f23a579a7a517842000e6741d4ecca7766c8738 Fix crafting results with multiple recipes showing unexpected quantities
