### ISSUE TITLE
Hot Air Balloons should accept water cells

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#38]
The Hot Air Balloon mod uses water buckets to cool the balloon. It would be nice if alternatively IndustrialCraft^2's water cells could be used.

**Comment by mushroomhostage** [comment]
Water cells stack making them more convenient than buckets. For balance purposes, they could be consumed in the process (like using lava cells in a geothermal generator or lava bucket in a stone furnace). Also Forestry has its own water cans with a similar purpose.

**Comment by unrealghostgamer** [comment]
sounds good

**Comment by mushroomhostage** [comment]
Still thinking whether I should do this.. would be cool, but now we have helicopters too, and the mod is open source., maybe enhance it to accept fuel instead?

**Comment by mushroomhostage** [comment]
Decided not to do this, would rather keep Hot Air Balloons as a mid-tier vehicle and THX Helicoper as a more powerful upper-tier. The lack of stacking water buckets for Hot Air Balloons provides a balanced trade off.
