### ISSUE TITLE
Options > Global Mod Settings crashes GuiAPI to install configuration

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#41]
If you go to Options > Global Mod Settings, Minecraft will crash with an error:

"GuiAPI has detected that it was not installed directly into the minecraft jar as required. If you are trying to use a mod manager such as MyCraft, or you are trying to use Modloader's mods folder, this would cause this issue. Please install directly into the minecraft jar in order for GuiAPI to work correctly"

Details at https://gist.github.com/138e6ebd3f51aabc7097

**Comment by mushroomhostage** [comment]
This occurs because of how GuiAPI is installed with SK's Launcher, even though it soft-mods the jar GuiAPI still is unable to find its theme files relative to its install path. 

Not really using GuiAPI, it is only required for Mo' Creatures to run. Players do not need to use it, as its used to change Mo' Creatures spawn settings, but they're configured on the server. Only needed to install it into the jar once, to create the config to copy over: https://github.com/mushroomhostage/exphc/blob/master/1.2.5/mods/mocreatures/guiconfig.properties

Fix is to install into the jar.. but this adds confusing complexity to the setup process, especially since GuiAPI is the only mod which requires it – even those which modify the jar, including ModLoader and Forge, can cope with soft modding just fine.

**Comment by mushroomhostage** [comment]
Open source: https://github.com/ShaRose/GuiAPI

**Comment by mushroomhostage** [comment]
"[Bypassed the GUI-API .minecraft directory check](https://github.com/TechnicPack/Technic/commit/18e76e75df0f683f1c2d75791698777c2a4b51d7)"

**Comment by mushroomhostage** [comment]
Would like to fix this, but not really needed, since users shouldn't need to access the mod configuration.. and it wouldn't even have any affect on the server if the options were changed. Fixing would be nice, but no longer tracking this.

**Comment by mushroomhostage** [comment]
Hit in the wild. Maybe try to fix in an optional update (1.2.5rev4b?)? Option to hide this button?

**Comment by mushroomhostage** [comment]
Maybe just hide in SMP?

**Comment by mushroomhostage** [comment]
Its actually very easy to get rid of this button. According to the docs https://github.com/mushroomhostage/GuiAPI/blob/master/readme.md it is added by a base edit to GuiOptions.class (obfuscated 'cd'), which is its only base edit. 

https://github.com/downloads/mushroomhostage/GuiAPI/GuiAPI-0.14.2-1.2.5+no-options.zip

Tested on 1.2.5rev5 test server. Mo' Creatures is unaffected.

**Comment by dash16** [comment]
"Necromancer powers, raise this thread from the dead!"

I hit this crash in 1.12.2 with Mo' Creatures 12.0.3 on Forge 1.12.2-14.23.1.2607

https://pastebin.com/LkntDJkD

I'm not sure I understand the 'very easy' way to get rid of the button.  Do I have to edit the jar file myself?

**Comment by tristanpoland** [comment]
I am having trouble removing the same button, I have tried using the fancymenu mod to edit the options menu and hide it, but it does not show up in the editor's GUI
<img width="1003" alt="Screen Shot 2021-06-10 at 9 58 58 AM" src="https://user-images.githubusercontent.com/34868944/121538079-7fd65480-c9d2-11eb-9f0f-444f8b573e21.png">
<img width="810" alt="Screen Shot 2021-06-10 at 9 58 50 AM" src="https://user-images.githubusercontent.com/34868944/121538127-8795f900-c9d2-11eb-81d4-0805856ae0fe.png">
