### ISSUE TITLE
FreeTrade help and hints

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#47]
When a trade is posted, it should say that you can type /want to view help on how to use the command. And /want (or /want help) should provide some examples of item specifications (10coal, #coal, dpick/100%, dpick/st). To encourage trading and explain the mysterious "Player wants X for Y" messages.

**Comment by unrealghostgamer** [comment]
sorry not been on in ages been caught up with something, i hope to be on soon, never used the /trade personally.

**Comment by mushroomhostage** [comment]
Hey no problem. PM me on Reddit (or on here, but I'm not sure how to send private messages on GitHub) and I'll send you the new setup instructions; I've since upgraded the server to 1.2.5, its way better now :).

As for this ticket, there has been some more interest in this trading system lately, but its kind of obscure. Messages now show what command you can type to accept (opposite of the existing /want order), and /want now has some examples of item specifications.

[master df3357f] FreeTrade help and hints https://github.com/mushroomhostage/exphc/issues/47
 1 files changed, 2 insertions(+), 0 deletions(-)

**Comment by mushroomhostage** [comment]
Deployed, should take effect on next server restart
