### ISSUE TITLE
Recipe conflict WRCBE Stone Bowl and JFM Guttering

### ISSUE THREAD

**Issue by mushroomhostage** [mushroomhostage/exphc#54]
The recipe:

```
s s
 s
```

where s = Stone (1), crafts to both:

Stone Bowl 6407 from Wireless Redstone Chicken Bones Edition
Guttering (Straight) 6284 from Jammy Furniture Mod

from pheeDrICK: "Before your last update [1.2.5rev3] I could craft the bowl in a normal crafting table and the guttering in the RP2 Project Table.."

**Comment by mushroomhostage** [comment]
For guttering how about:

```
s s
sss
```

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/exphc/commit/2ca6f43f6fc2dcd7e73eb06410ceeccfceefcf64 RecipeRepo: block Guttering (Straight) 6284 from Jammy Furniture Mod since conflicts with Stone Bowl 6407 from Wireless Redstone Chicken Bones Edition 

Now can craft stone bowls

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/ExphcTweaks/commit/d7d369a30a40f4fb431521c9f9dc487d3f476b26 Add alternate recipe for Jammy Furniture Mod guttering

**Comment by mushroomhostage** [comment]
Fixed & deployed

**Comment by cpypcy** [comment]
Oh i didn't saw it :D Sorry!

**Comment by mushroomhostage** [comment]
Well, there's still an issue where the recipe doesn't show up on the client in NEI. Tracking that in https://github.com/mushroomhostage/exphc/issues/84
