### ISSUE TITLE
Advanced buildcraft objects uncraftable

### ISSUE THREAD

**Issue by cpypcy** [mushroomhostage/exphc#79]
Since last update 2012.08.05 they vanished from base and are not craftable, they give me errors, any idea where might the problem?

**Comment by mushroomhostage** [comment]
Unfortunately, I removed Additional Buildcraft Objects in this update (couldn't get it to [work well](https://gist.github.com/e00d0880ac8f9f95bf9b) with the latest mods). It is no longer installed on the server so it can't be crafted.

That it is still on the client is an oversight on my part.. to remove it you can go to SK's Launcher > Addons and uncheck AdditionalBuildcraftObjects, or repeat the setup instructions – I fixed this in the latest client configuration, which now no longer includes the removed mods (there were a couple other old versions lying around as well, though they weren't activated). 

I'll miss this mod too, its a shame to remove it, but hopefully having newer versions of most of all the other mods instead is a worthwhile tradeoff. FYI a detailed change log for ExpHC 1.2.5rev5 (the 2012/08/04 update) is available here: http://www.reddit.com/r/mcservers/comments/tjbli/anarchy_experimental_hardcore_postapocalyptic/c5ocujo

**Comment by cpypcy** [comment]
Will it return?

**Comment by mushroomhostage** [comment]
Not if I can't get it to work :/
