### ISSUE TITLE
Power Converters geothermal mk2 banned?

### ISSUE THREAD

**Issue by overclock22** [mushroomhostage/exphc#83]
I hear they are overpowered but someone reasoned on a post that a bunch of engines on a  HV converter will produce the same results so mayhbe unban them? Maybe nerf them a bit? I like the idea of the geotehrmal generator but it seems the best option is stacks of solar array. 

I will try and find the exact post with the reasoning but it is along those lines.

**Comment by mushroomhostage** [comment]
Haven't changed anything myself to ban them.. Need to confirm, but I think the only difference was that mark II accepted piped lava, but now regular geothermal generators already do, so the II in Power Converters is obsolete (but remains for backwards-compatibility).

**Comment by overclock22** [comment]
That makes perfect sense. I just couldn't construct it so I thought it might've come banned by default in the config.

**Comment by mushroomhostage** [comment]
Indeed. From config/PowerConverters.cfg, it is disabled by default:

```
Enable.GeothermalMk2=false
```

seems to be very similar to the regular IC2 [Geothermal Generator](http://wiki.industrial-craft.net/index.php?title=Geothermal_Generator), though it does have a configurable Rate.GeoMk2EUPerTick=20 (same as mkI). Suppose it could be enabled with a higher EU/t, but probably not a sufficient cost to add a tank (and nothing else) to get a higher energy output. May change in the future, but going to leave this as-is for now..

**Comment by mushroomhostage** [comment]
Actually, I suppose I can enable the Geothermal Generator Mk2, even with the defaults. It is identical to the Geothermal Generator, except only accepts piped lava (no GUI), but it has a nicer-looking block texture in my opinion (including particles emanating from the top when it is active). It doesn't use any additional block IDs, and can be enabled purely server-side. 

Should be available now after the next server restart. Note, the recipe still won't be visible in NEI until the next client update (1.2.5rev5c+), but you should still be able to craft it (geothermal generator + tank) and use it.

**Comment by mushroomhostage** [comment]
Enabled now on server, craftable with Geothermal Generator + Tank (but note, it has no GUI, only accepts piped lava, and produces the same EU/t output – but it looks cooler ;)
