### ISSUE TITLE
Guttering and stone bowl use same recipe

### ISSUE THREAD

**Issue by cpypcy** [mushroomhostage/exphc#84]
Can you change guttering recipe or fix something that guttering will be craftable?

**Comment by mushroomhostage** [comment]
Hmm, I thought I fixed this: https://github.com/mushroomhostage/exphc/issues/54 - need to double-check..

Can you craft with guttering in this shape?

```
S S
SSS
```

where S = stone

**Comment by mushroomhostage** [comment]
Will use this issue to track making the recipe show up properly on the client in NEI

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/ExphcTweaks/commit/7d5da24c8b85253bc23576356e1dac83e6eb59b1

**Comment by mushroomhostage** [comment]
Repeat the setup instructions and this should now be fixed (1.2.5rev5c)

**Comment by mushroomhostage** [comment]
Actually server had to restart first... verified fix now. Guttering (straight) is now: (S = stone)

```
___
S_S
SSS
```

(note, at bottom)

Will appear in NEI after repeating setup instructions (fixed in rev5c)
