### ISSUE TITLE
Empty fish bowl recipe problem (Mo' Creatures fish bowl / Trees++ glass cup recipe conflict)

### ISSUE THREAD

**Issue by cpypcy** [mushroomhostage/exphc#90]
Empty fish bowl and Glass Cup have same recipe, you can't craft bowl. :(

**Comment by mushroomhostage** [comment]
You can use a [QuickBench](http://dev.bukkit.org/server-mods/quickbench/) as a workaround to craft the fish bowl until I fix this conflict. Craft it with a Crafting Table + Book, place it, then right click with glass in your inventory then you'll be able to craft both glass cups and fish bowls.

**Comment by mushroomhostage** [comment]
Suppose I could change it to use glass panes instead, in the same shape

**Comment by cpypcy** [comment]
I'll try that quickbench.

**Comment by mushroomhostage** [comment]
Workaround in ExphcTweaks 
https://github.com/mushroomhostage/ExphcTweaks/commit/1bc78b1a91c3d2b1059adf082e4d86881475c265 Change Trees++ recipe for glass cups to use panes to fix conflict with Mo' Creatures fish bowl

**Comment by mushroomhostage** [comment]
https://github.com/mushroomhostage/exphc/commit/90a02448fa06b68e97d5e3b074794063683967a4 RecipeRepo: Trees++: remove glass cup recipe so it can be added in ExphcTweaks

**Comment by mushroomhostage** [comment]
Repeat the setup instructions and this should now be fixed (1.2.5rev5c)

Mo' Creatures fish bowl is as before
Trees++ glass cup is now made with glass panes

**Comment by mushroomhostage** [comment]
Server had to restart for this changed to be applied, verified fixed now.

**Comment by mushroomhostage** [comment]
Also suggested to Trees++ author: http://www.minecraftforum.net/topic/1028159-125trees-v1346-forgesmpbukkit36-trees7-biomes10-flowers/page__st__1100__gopid__17408330#entry17408330
