### ISSUE TITLE
Railcraft tunnel bore eats its contents

### ISSUE THREAD

**Issue by overclock22** [mushroomhostage/exphc#95]
Is this intended or something known? 

I filled a tunnel bore up that was stationary in my area and upon returning today the diamond bore and stacks of gravel and tracks are gone :C

**Comment by mushroomhostage** [comment]
Not intended. I've updated the port of Railcraft 5.4.7 to smb's latest r4 (will take effect on next server restart), but I still see this problem. Seems to happen every release of Railcraft and has to be fixed :). 5.3.3 also has a fix "TBM NBT data fixed, rails and gravel are now used up and placed correctly", but I guess 5.4.7 does not yet have it.

Will update the port when its fixed..

**Comment by mushroomhostage** [comment]
Reported upstream http://www.mcportcentral.co.za/index.php?topic=3641.0

**Comment by overclock22** [comment]
The bore also doesn't eat fence posts as it makes its ponderous way. It just stops dead at them. Is this something you can change in the config or is this something that was intended? 

It eats wood planks but fence posts are a problem. On a side note I cannot get the magma crucible to produce lava. 

Start it up, feed it mj and stick a bucket in but nothing. I don't want to get off track but I feel like im making a lot of comments here :D

**Comment by mushroomhostage** [comment]
For the magma crucible you need to feed it netherrack. 

I could change what blocks the TBM mines. Currently I've added various ores from other mods, but could add fences too.

**Comment by overclock22** [comment]
Just skipped right over the first line on the thermal wiki, feed cobblestone, etc, etc.... :C

If you would add wooden fences at least so when the bore meets an abandoned mine (which is majority of the underground) it doesnt stop dead burning fuel.

**Comment by mushroomhostage** [comment]
Added fences to mineable blocks: https://github.com/mushroomhostage/exphc/commit/e81a1665337fcad9212877850328ddd8b7eda0b5
Will take effect on next restart

**Comment by mushroomhostage** [comment]
Btw if you want to make lava from pure energy, you can use a Lava Fabricator - but it is very expensive

**Comment by overclock22** [comment]
Lava is extremely easy to make with a squeezer and uranium, Its crazy even. Ive been trying to produce radioactive waste with it. Ive just been toying around with the mods I dont know and magma crucible sounded cool. 

Im glad to see the fence addition thought I was set back by a ghost creeper killing me : /

What are the rules for them because I feel like they ignore armour but the mod page isnt very descriptive. I just died with 3 pieces of quantum on and jetpack. Thats 10 armour and 10 hearts but still insta gibbed, are creepers that deadly that 10 armor is ignored if up close? Only the ghost ones ever get that close.

**Comment by overclock22** [comment]
Just noticed tracks laid on the ground also stop the bore. Would appreciate if you could add that as well. Going to be impossible to setup subway tunnels with it stopping every 3 minutes XD

**Comment by mushroomhostage** [comment]
https://github.com/MinecraftPortCentral/CraftBukkit/pull/11

**Comment by mushroomhostage** [comment]
Need to update to MCPC #180+

**Comment by mushroomhostage** [comment]
For the TBM mineable blocks:

https://github.com/mushroomhostage/exphc/commit/1f3909fa382e0f92cdd34c4509407c61af55f3c2 Railcraft: TBM: allow mining vanilla planks, track, and cobweb to make mining through abandoned mineshafts easier.

Not sure about the ghost creepers, but, I know they are very deadly, many have died from them.

For the Railcraft TBM inventory loss bug, tested updating to 180 (+1.2.5-R5.0 pull requests while I was at it: https://github.com/MinecraftPortCentral/Bukkit/pull/2 + https://github.com/MinecraftPortCentral/CraftBukkit/pull/12 , using custom build https://github.com/downloads/mushroomhostage/CraftBukkit/craftbukkit-1.2.5-R5.0-MCPC-SNAPSHOT-180+r5.jar + internal mods), the change https://github.com/MinecraftPortCentral/CraftBukkit/pull/11 does fix the issue. Will be active on next server restart.

**Comment by mushroomhostage** [comment]
Fix deployed! TBM inventory should now be preserved across chunk reload.
